export const projects = [
  {
    tag: "Internal · Web",
    name: "Academic Resource Coordination System",
    slug: "academic-resource-system",
    desc: "A closed-source internal web platform developed for an educational organisation to streamline distribution of academic materials and collaboration workflows.",
    year: "2025",
    problem: "Fragmented communication channels and unstructured file sharing caused delays in accessing verified academic resources and coordinating student project groups.",
   solution: "Architected a modular full-stack system with role-based access control to ensure structured distribution of verified academic resources across departments. Implemented hierarchical content organisation, search indexing, and channel-based collaboration workflows to reduce dependency on informal communication groups. Designed asynchronous assignment tracking pipelines with status visibility for coordinators and participants. Optimised frontend rendering performance for low-bandwidth campus networks and integrated secure authentication flows aligned with institutional usage policies.",
    impact: "Improved internal resource accessibility and coordination efficiency.",
    techStack: ["Next.js", "React", "Node.js", "Firebase", "Tailwind CSS"],
    codeAccess: "Closed-source",
  },
  {
    tag: "Embedded · IoT",
    name: "Smart Facility Environment Monitoring",
    slug: "smart-facility-monitoring",
    desc: "An embedded monitoring system providing real-time environmental telemetry and remote device control.",
    year: "2025",
    problem: "Manual monitoring of indoor conditions resulted in inconsistent comfort levels and inefficient energy usage.",
   solution: "Designed a distributed sensor network using microcontroller nodes capable of continuous environmental sampling and local threshold evaluation to reduce central processing load. Implemented reliable telemetry transmission with periodic heartbeat signalling to detect node failures. Built a lightweight monitoring dashboard enabling real-time visualization of environmental parameters and remote actuation of connected devices. Engineered fallback manual override logic and power-efficient sampling strategies to ensure long-duration deployment stability in shared residential infrastructure.",
    impact: "Reduced manual intervention in facility management operations.",
    techStack: ["Embedded C++", "Microcontrollers", "Python", "Web Dashboard"],
    codeAccess: "Closed-source",
  },
  {
    tag: "Mobile · Realtime",
    name: "Occupancy Intelligence Application",
    slug: "occupancy-intelligence",
    desc: "A mobile solution designed for institutional space utilization tracking using distributed sensor inputs.",
    year: "2024",
    problem: "Users faced inefficiencies due to lack of visibility into seating availability during peak usage hours.",
   solution: "Developed a real-time occupancy intelligence pipeline aggregating pressure-sensor signals through edge processing layers before synchronizing with a central availability service. Implemented spatial mapping logic to convert raw sensor states into dynamically updated occupancy heat-maps optimised for mobile interaction. Designed queue-resilient update mechanisms to prevent stale seat status during peak usage bursts. Integrated adaptive refresh strategies and lightweight caching to maintain usability under high concurrent access conditions.",
    impact: "Improved navigation efficiency in high-density environments.",
    techStack: ["React Native", "Node.js", "MongoDB", "IoT Sensors"],
    codeAccess: "Closed-source",
  },
  {
    tag: "Tool · Algorithms",
    name: "Interactive Algorithm Simulation Suite",
    slug: "algorithm-simulation-suite",
    desc: "A browser-based internal visualization tool for structured algorithm training sessions.",
    year: "2024",
    problem: "Static teaching approaches failed to provide intuitive understanding of algorithm behaviour.",
   solution: "Engineered an event-driven algorithm simulation engine capable of deterministic step execution and state snapshotting for multiple data structure transformations. Implemented timeline-based control systems allowing users to replay, pause, or inspect intermediate computational states during algorithm traversal. Designed extensible rendering abstractions supporting graph structures, array manipulations, and path exploration visual flows. Integrated structured test scenarios and performance instrumentation to ensure consistent behaviour across varying input scales during instructional sessions.",
    impact: "Improved conceptual clarity during internal training programs.",
    techStack: ["JavaScript", "Canvas", "Vite", "Testing Tools"],
    codeAccess: "Closed-source",
  },
];